<style>
body {font-family: consolas; background-color: white;
background-image: url("img/background2.jpg");
/*background-repeat: repeat-y;*/
}
* {box-sizing: border-box;}

.input-container {
    display: -ms-flexbox; /* IE10 */
    display: flex;
    width: 100%;
    margin-bottom: 15px;
}

.icon {
    padding: 10px;
    background: #009a7e;
    color: white;
    min-width: 40px;
    text-align: center;
    font-size: 18px;
}

.input-field {
    width: 100%;
    padding: 10px;
    outline: none;
}

.input-field:focus {
    border: 2px solid #009a7e;
}

/* Set a style for the submit button */
.btn {
    background-color: #009a7e;
    color: white;
    padding: 15px 20px;
    border: none;
    cursor: pointer;
    width: 100%;
    opacity: 0.9;
}

.btn:hover {
    opacity: 1;
}

.col-md-3{
margin: 0 auto;
}
h2, label{color:white;}
.login_style{
    padding: 70px 0;
    border: 3px solid none;
    text-align: center;
}
</style>


<div class="container">
<div class="login_style">

<?php
$this->headTitle('Sign in');

$this->mainMenu()->setActiveItemId('login');

$form->get('email')->setAttributes([
    'class'=>'input-field', 
    'placeholder'=>'Email address',
    'required' => true,
    'autofocus' => true
    ])
    ->setLabelAttributes([
        'class' => 'sr-only'
    ]);

$form->get('password')->setAttributes([
    'class'=>'input-field', 
    'placeholder'=>'Password',
    'required' => true,
    ])
    ->setLabelAttributes([
        'class' => 'sr-only'
    ]);
?>

<div class="row">

    <div class="col-md-offset-12 col-md-3">
        <form class="form-signin" method="post">
            <h2 class="form-signin-heading">User Signin</h2>
            <?php if ($isLoginError): ?>
            <div class="alert alert-warning" role="alert">
                Incorrect login and/or password. 
                <a href="<?= $this->url('reset-password') ?>">Forgot password?</a>
            </div>
            <?php endif; ?>

            <div class="input-container">
            <i class="fa fa-envelope icon"></i>
            <?= $this->formLabel($form->get('email')); ?>
            <?= $this->formElement($form->get('email')); ?>
            </div>
            

            <div class="input-container">
            <i class="fa fa-key icon"></i>
            <?= $this->formLabel($form->get('password')); ?>
            <?= $this->formElement($form->get('password')); ?>
            </div>
            <div class="input-container">
            <div class="checkbox">
                <label>
                    <?= $this->formElement($form->get('remember_me')); ?> Remember me
                </label>
            </div>
            </div>
            <?= $this->formElement($form->get('redirect_url')); ?>
            <?= $this->formElement($form->get('csrf')) ?>
            <button class="btn" type="submit">Sign in</button>
        </form>
    </div>
</div>

</div>
</div>